---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
     - name: creating workpress container
       lxd_container:
        name: wordpress
        source:
           type: image
           fingerprint: 7a7ff654cbd8
        wait_for_ipv4_addresses: yes
        state: started

